### ISSUE TITLE
Facing an issue with UI of this project

### ISSUE THREAD

**Issue by ShaikhNargis** [dsinyakov/angularjs-play-blog-app#1]
Hi,
I need your help with regard to blog published on totpal site i.e.http://www.toptal.com/java/building-modern-web-applications-with-angularjs-and-play-framework. 
I have done all mandatory / required steps to run this project,though it is running perfectly. I can not  see the proper bootstrap UI as shown in your blog. I had followed similar steps mentioned for calories tracker application as well. being newbie in this kind a architecture i would like to know what are those files missing to achieve complete UI as shown in your blog as well as in GITHUB project.
I've attached a screenshot the UI which i am getting. Appreciate if you can help me i this regard.

![2015-06-25 15_55_29-localhost_9000_ _](https://cloud.githubusercontent.com/assets/13047844/8352540/887c7dd2-1b53-11e5-85d4-133ee7f92176.png)

**Comment by dsinyakov** [comment]
Hi,

How does your client/bower.json file look like?

**Comment by ShaikhNargis** [comment]
Hi,
client/bower.json:

{
  "name": "mytodo",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0"
  },
  "devDependencies": {
    "angular-mocks": "^1.3.0"
  },
  "appPath": "app",
  "moduleName": "mytodoApp"
}

**Comment by dsinyakov** [comment]
bower.son looks good and contains bootstrap. Please try to run

```
bower install
```

in your client dir to install all the dependencies
